Repository nhsx/au-azure-databricks, pull requests merged in 2022-04, with the labels that each got.

#95 Adjustment to processing
  analytics/dbrks_nhs_app/dbrks_nhs_app_registered_population_week_prop.py
  ingestion/dbrks_nhs_app/dbrks_nhs_app_usage_raw.py
Labels: bug

#97 Created notebooks for new NHS files
  ingestion/dbrks_nhs_app/dbrks_nhs_app_device_raw.py
  ingestion/dbrks_nhs_app/dbrks_nhs_app_jumpoff_raw.py
Labels: enhancement

#98 Dev
  ingestion/dbrks_nhs_app/dbrks_nhs_app_device_raw.py
  ingestion/dbrks_nhs_app/dbrks_nhs_app_jumpoff_raw.py
Labels: enhancement

#100 M013_databricks_dev
  analytics/dbrks_socialcare_digitalrecord/dbrks_socialcare_digitalrecord_month_count_prop.py
  ingestion/dbrks_socialcare_digitalrecord/dbrks_socialcare_digitalrecord_raw.py
Labels: enhancement

#101 Dev
  analytics/dbrks_socialcare_digitalrecord/dbrks_socialcare_digitalrecord_month_count_prop.py
  ingestion/dbrks_socialcare_digitalrecord/dbrks_socialcare_digitalrecord_raw.py
Labels: enhancement

#104 bug fix: date moving around NHSD webpage
  ingestion/dbrks_gp_records_api/dbrks_gp_records_api_raw.py
Labels: bug, enhancement

#105 Dev
  ingestion/dbrks_gp_records_api/dbrks_gp_records_api_raw.py
Labels: bug, enhancement

#106 Added time series functionality and date cleanup
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: enhancement

#108 Fix to remove DQ issue on Date completed field
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: bug
