Repository nhsx/au-azure-databricks, pull requests merged in 2022-02, with the labels that each got.

#35 Shcr update
  analytics/dbrks_gp_practices_it_standards/dbrks_primarycare_gp_it_standards_year_count_prop.py
  analytics/dbrks_gp_practices_it_standards/dbrks_primarycare_gp_it_standards_year_prop.py
  analytics/dbrks_online_consultations/dbrks_primarycare_online_consultation_gp_practice_supplier_week_count.py
  ingestion/dbrks_gp_practices_it_standards/dbrks_gp_it_standards_raw.py
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: Refactor

#37 DSPT CSUs/Trusts/CCGs
  analytics/dbrks_dspt_nhs/dbrks_cybersecurity_dspt_nhs_csu_ccg_standards_month_count_prop.py
  analytics/dbrks_dspt_nhs/dbrks_cybersecurity_dspt_nhs_trusts_standards_month_count_prop.py
Labels: Refactor

#38 Adjustments to databricks
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: Refactor

#39 shcr refactor code
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: Refactor

#40 Adjustments and comments
  ingestion/dbrks_shared_care_record/dbrks_shared_care_record_raw.py
Labels: Refactor

#42 Bug_fix_dsppt_gp_practices
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_exceed_year_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_meet_exceed_year_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_nosubmission_year_count_prop.py
  ingestion/dbrks_registered_gp_practices/dbrks_registered_gp_practices_raw.py
Labels: enhancement

#43 Final_dev_DSPT_gp_practices_monthly
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_meet_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_nosubmission_month_count_prop.py
Labels: enhancement

#44 Bug_fix_for_DSPT_gp_practice_historical
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_meet_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_nosubmission_month_count_prop.py
Labels: bug, enhancement

#45 dev_final_orchestractor_gp_practice_dspt
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_meet_exceed_month_count_prop.py
  analytics/dbrks_dspt_gp_practices/dbrks_cybersecurity_dspt_gp_practices_standards_nosubmission_month_count_prop.py
  orchestration/dbrks_dspt_gp_practices_snapshot_orchestrator.py
Labels: enhancement

#46 Added NHS app ingestion notebook
  ingestion/dbrks_nhs_app/dbrks_nhs_app_usage_raw.py
Labels: enhancement

#47 Dev nhs app
  analytics/dbrks_nhs_app/dbrks_nhs_app_registered_population_week_prop.py
  ingestion/dbrks_nhs_app/dbrks_nhs_app_usage_raw.py
  orchestration/dbrks_nhs_app_orchestrator.py
Labels: enhancement
